import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";

const notoserifbengali = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoserifbengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navber></Navber>
        <div>{children}</div>
        
        </body>
    </html>
  );
}
